const ActionTypes = {
  LIST_NOW_PLAY: "LIST_NOW_PLAYR",
  LIST_POPULAR: "LIST_POPULAR",
  SELECTED_TYPE_MOVIE: "SELECTED_TYPE_MOVIE",
  DETAIL_MOVIE: "DETAIL_MOVIE",
  SET_PARAM: "SET_PARAM",
};
export default ActionTypes;
